// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetstatusServiceStatus struct {
	App        *string `json:"app,omitempty"`
	Moto       *string `json:"moto,omitempty"`
	Notes      *int    `json:"notes,omitempty"`
	Os         *string `json:"os,omitempty"`
	PhpVersion *string `json:"php_version,omitempty"`
	Status     string  `json:"status"`
	Time       *string `json:"time,omitempty"`
	Users      *int    `json:"users,omitempty"`
}

func (o *GetstatusServiceStatus) GetApp() *string {
	if o == nil {
		return nil
	}
	return o.App
}

func (o *GetstatusServiceStatus) GetMoto() *string {
	if o == nil {
		return nil
	}
	return o.Moto
}

func (o *GetstatusServiceStatus) GetNotes() *int {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *GetstatusServiceStatus) GetOs() *string {
	if o == nil {
		return nil
	}
	return o.Os
}

func (o *GetstatusServiceStatus) GetPhpVersion() *string {
	if o == nil {
		return nil
	}
	return o.PhpVersion
}

func (o *GetstatusServiceStatus) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetstatusServiceStatus) GetTime() *string {
	if o == nil {
		return nil
	}
	return o.Time
}

func (o *GetstatusServiceStatus) GetUsers() *int {
	if o == nil {
		return nil
	}
	return o.Users
}

type GetstatusResponse struct {
	ContentType   string
	ServiceStatus *GetstatusServiceStatus
	StatusCode    int
	RawResponse   *http.Response
}

func (o *GetstatusResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetstatusResponse) GetServiceStatus() *GetstatusServiceStatus {
	if o == nil {
		return nil
	}
	return o.ServiceStatus
}

func (o *GetstatusResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetstatusResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
