// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetuserUser struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Email     *string `json:"email,omitempty"`
	ID        *int    `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *GetuserUser) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetuserUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetuserUser) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetuserUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetuserUser) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type GetuserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	User        *GetuserUser
}

func (o *GetuserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetuserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetuserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetuserResponse) GetUser() *GetuserUser {
	if o == nil {
		return nil
	}
	return o.User
}
